#!/usr/bin/env bash

function usage {
  cat <<EOF
  Usage: $(basename $0) [<commit>...]

  Checks if messages in the specified commit range conform to
  a conventional commit message, see:
  https://www.conventionalcommits.org/en/v1.0.0/#specification

  Takes an optional range specification of commits to check.
  If no range is given, HEAD^..HEAD is used to target
  only the current commit.

EOF
}

range="HEAD^..HEAD"
if [[ ! -z "$1" ]]; then
        range="$1"
fi

CONVENTIONAL_REGEX='^(fix|feat|chore|docs)(\([[:alnum:]_]+\))?!?:[[:space:]][^[:space:]](.*)[^.]$'

for sha in $(git rev-list "$range"); do
if [[ "$msg" =~ $CONVENTIONAL_REGEX ]]; then
	echo "good commit message:"
        echo "$msg"
else
	echo "bad commit message:"
        echo "$msg"
	exit 1
fi
done
